export const data = [
  {
    id: "1",
    cover: "/banner.jpg",
    profile: "/hero/person1.jpg",
    name: "Medi Kingura",
    address: "Kinshasa, RDC",
    email: "medikingura86@gmail.com",
    phone: "+243 991 795 930",
    facebook: "https://www.facebook.com/medi.kingura.7",
    instagram: "https://www.instagram.com/medikingura/",
    linkedin: "https://www.linkedin.com/in/medi-kingura/",
    whatsapp: "https://web.whatsapp.com",
  },
  {
    id: "2",
    cover: "/banner.jpg",
    profile: "/hero/person2.jpg",
    name: "Plamedie Kingura",
    address: "Kinshasa, RDC",
    email: "israellakingura@gmail.com",
    phone: "+243 999 999 999",
    facebook: "https://www.facebook.com/medi.kingura.7",
    instagram: "https://www.instagram.com/medikingura/",
    linkedin: "https://www.linkedin.com/in/medi-kingura/",
    whatsapp: "https://web.whatsapp.com",
  },
  {
    id: "3",
    cover: "/banner.jpg",
    profile: "/hero/person3.jpg",
    name: "Joseph Mulumba",
    address: "Kinshasa, RDC",
    email: "lepropulseur@gmail.com",
    phone: "+243 999 999 999",
    facebook: "https://www.facebook.com/medi.kingura.7",
    instagram: "https://www.instagram.com/medikingura/",
    linkedin: "https://www.linkedin.com/in/medi-kingura/",
    whatsapp: "https://web.whatsapp.com",
  },
];
